# -*- coding: utf-8 -*-
"""Statistik Deskriptif

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNMO5J_gd7ViOM6RZJeS08IsYF_WPSa6
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_excel('trx_cleaned.xlsx')

# Konversi received_time menjadi datetime
df["received_time"] = pd.to_datetime(df["received_time"], errors='coerce')

# Statistik numerik untuk trx_value
print("Statistik Deskriptif trx_value:")
print(df["trx_value"].describe())

# Statistik kategorikal
print("\nDistribusi channel_type:")
print(df["channel_type"].value_counts())

print("\nDistribusi biller_name:")
print(df["biller_name"].value_counts())

print("\nDistribusi operator_code:")
print(df["operator_code"].value_counts())

# Bar chart Top 10 Biller
plt.figure(figsize=(10,5))
top_billers = df["biller_name"].value_counts().head(10)
sns.barplot(x=top_billers.values, y=top_billers.index, palette="Blues_d")
plt.title("10 Biller Terbanyak")
plt.xlabel("Jumlah Transaksi")
plt.ylabel("Biller")
plt.show()