# -*- coding: utf-8 -*-
"""Clustering Layanan Asuransi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mu1UPYpkG9v5BbMdsGuprbkfEJc44Zjx
"""

# CLUSTERING LAYANAN ASURANSI

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans

df = pd.read_excel('trx_cleaned.xlsx')

asuransi_services = ['BPJS Kesehatan', 'BPJS Ketenagakerjaan (EPS)', 'Prudential Lanjutan', 'BPJS KETENAGAKERJAAN BPU']
df_asuransi = df[df['biller_name'].isin(asuransi_services)].copy()

# Proses waktu transaksi
df_asuransi['received_time'] = pd.to_datetime(df_asuransi['received_time'], errors='coerce')
df_asuransi['day_of_week'] = df_asuransi['received_time'].dt.dayofweek  # Senin=0, Minggu=6

# Encode operator_code jadi angka (opsional)
df_asuransi['operator_encoded'] = LabelEncoder().fit_transform(df_asuransi['operator_code'].astype(str))

features = ['trx_value', 'day_of_week']
X = df_asuransi[features].dropna()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Elbow Method
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []
K_range = range(1, 6)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(10, 5))
plt.plot(K_range, inertia, 'bo-')
plt.xlabel('Jumlah Cluster')
plt.ylabel('Inertia')
plt.title('Elbow Method untuk Menentukan Jumlah Cluster Optimal')
plt.grid(True)
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10) # Added n_init to suppress warning
df_cluster = df_asuransi.loc[X.index].copy()
df_cluster['Cluster'] = kmeans.fit_predict(X_scaled)

# Tambahkan koordinat centroid
centroids = scaler.inverse_transform(kmeans.cluster_centers_)
centroids_df = pd.DataFrame(centroids, columns=features)

# Visualisasi hasil cluster
plt.figure(figsize=(12, 6))
colors = ['red', 'blue', 'green', 'magenta']

for i in range(4):
    cluster_data = df_cluster[df_cluster['Cluster'] == i]
    plt.scatter(
        cluster_data['day_of_week'],
        cluster_data['trx_value'],
        s=10,
        color=colors[i],
        label=f'Cluster {i}'
    )

# Plot centroid
plt.scatter(
    centroids[:, 1], # day_of_week is the second feature
    centroids[:, 0], # trx_value is the first feature
    s=50,
    marker='x',
    color='black',
    label='Centroid'
)
# Label dan format sumbu
plt.title('Clustering Layanan Asuransi Berdasarkan Nilai Transaksi dan Hari Transaksi')
plt.xlabel('Hari Transaksi (0=Senin ... 6=Minggu)')
plt.ylabel('Nilai Transaksi (Rp)')
plt.grid(True)

# Format sumbu Y jadi format Rupiah
plt.gca().yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f'Rp{x:,.0f}'))

plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# Statistik deskriptif per cluster
stats = df_cluster.groupby('Cluster')[['trx_value']].agg(['count'])
print("Statistik per Cluster:")
print(stats)