# -*- coding: utf-8 -*-
"""Clustering Layanan E-Wallet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAQh1EljY_ypYEj1HzKHwS_ntYzhXUle
"""

# Clustering Layanan E-Wallet
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans

df = pd.read_excel('trx_cleaned.xlsx')

# Filter: E-Wallet
ewallet_services = ['TopUp Ovo', 'Dana', 'TopUp Gopay', 'ShopeePay', 'iSaku', 'Link Aja']
df_net = df[df['biller_name'].isin(ewallet_services)].copy()

# Preprocessing kolom waktu dan fitur tambahan
df_net['received_time'] = pd.to_datetime(df_net['received_time'], errors='coerce')
df_net['hour'] = df_net['received_time'].dt.hour  # ekstrak jam dari waktu transaksi

# Encode operator_code jadi angka
df_net['operator_encoded'] = LabelEncoder().fit_transform(df_net['operator_code'].astype(str))

# Pemilihan fitur yang akan digunakan untuk clustering
features = ['trx_value', 'hour', 'operator_encoded']
X = df_net[features].dropna()

# Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Elbow Method
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []
K_range = range(1, 6)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(10, 5))
plt.plot(K_range, inertia, 'bo-')
plt.xlabel('Jumlah Cluster')
plt.ylabel('Inertia')
plt.title('Elbow Method untuk Menentukan Jumlah Cluster Optimal')
plt.grid(True)
plt.show()

# Clustering
kmeans = KMeans(n_clusters=3, random_state=42)
df_net_filtered = df_net.loc[X.index].copy()
df_net_filtered['Cluster'] = kmeans.fit_predict(X_scaled)

# Visualisasi hasil cluster
plt.figure(figsize=(12, 6))
scatter = sns.scatterplot(
    data=df_net_filtered,
    x='hour',
    y='trx_value',
    hue='Cluster',
    style='biller_name',
    palette='tab10'
)
plt.title('Clustering Layanan E-Wallet')
plt.xlabel('Jam Transaksi')
plt.ylabel('Harga Pembelian (Rp)')
plt.grid(True)

# Format sumbu Y jadi format Rupiah
plt.gca().yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f'Rp{x:,.0f}'))

# Penempatan legenda
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.tight_layout()
plt.show()

# Statistik tiap cluster
stats = df_net_filtered.groupby('Cluster')[['trx_value', 'hour']].agg(['count', 'mean', 'std', 'min', 'max'])
print("Statistik per Cluster:")
print(stats)

# Pencarian transaksi tertinggi
df_outlier = df_net_filtered[
    (df_net_filtered['biller_name'] == 'TopUp Ovo') &
    (df_net_filtered['trx_value'] > 5_000_000)
]

df_outlier

df_net_filtered.to_excel("hasil_cluster_e-wallet.xlsx", index=False)